### PR TITLE
squad_client: tux: change the way we name build tests

### PR DESCRIPTION
**Pull request by jscook2345**
This ended up being a lot more work than expected, with testing, retesting, rebasing, and trying to do things cleanly. I hope this all makes reviewing a bit easier. Thanks for your patience while I finished this up.

    squad_client: tux: change the way we name build tests

    Here is now naming will work now.

    Single builds use their build name, the first kconfig name, and a
    combined kconfig sha, all using data from the tuxsuite build.json.

    Ex: arm-clang12-defconfig-<sha>

    To create the combined kconfig sha, we download all of the fragments
    from the download_url (in build.json), combine them into a single file,
    and than take the sha of that file.

    Build sets use their build name and combine it with the target_arch,
    toolchain, and first kconfig name, all using data from the tuxsuite
    build.json.

    Ex: arm-gcc-8-allnoconfig

    To accomplish this we move this code into it's own module so we can
    test it as a unit and share it with other tuxsuite-related projects if
    needed.

    Additionally, we need to fix a test that sets an environment variable
    because it was having a side effect on other tests.

    Signed-off-by: Justin Cook <justin.cook@linaro.org>

### CODE REVIEW

**Comment by jscook2345** [comment]
This replaces #143. Between the changes, tests, and having to rebase a lot I ended up doing a new PR.

**Comment by jscook2345** [comment]
Blah, I forgot to mock the fetching of files from the download url. I will have to work on that tomorrow.

**Comment by jscook2345** [comment]
@roxell @chaws OK. Ready for review. Be gentle ;)

**Review by roxell — COMMENTED** [review]
"all: clean up some of the source"

Please elaborate what you mean, so its understandable in a few month.

**Comment by roxell** [comment]
"commands: submit_tuxbuild: name build tests using the tux module"

Whats the problem with the way we do it today?

**Comment by roxell** [comment]
"commands: submit_tuxbuild: build metadata using the tux module"

In what way will this improve the current source ?

**Comment by roxell** [comment]
"commands: submit_tuxbuild: load builds using the tux module"

Why is this a fix that would improve?

**Comment by roxell** [comment]
>    squad_client: tux: change the way we name build tests
>   
>    Here is now naming will work now.
>    
>    Single builds use their build name, the first kconfig name, and a
>    combined kconfig sha, all using data from the tuxsuite build.json.
>    
>    Ex: arm-clang12-defconfig-<sha>
>    
>    To create the combined kconfig sha, we download all of the fragments
>    from the download_url (in build.json), combine them into a single file,
>    and than take the sha of that file.

Important to highlight: We do this, since we don't want to get in to a changing chat due to the 'defconfig' file changes.

>    
>    Build sets use their build name and combine it with the target_arch,
>    toolchain, and first kconfig name, all using data from the tuxsuite
>    build.json.
>    
>    Ex: arm-gcc-8-allnoconfig
>    
>    To accomplish this we move this code into it's own module so we can
>    test it as a unit and share it with other tuxsuite-related projects if
>    needed.

Why?

**Comment by roxell** [comment]
There are a few trailing white spaces that you need to fix too please.

part from that it looks ok

**Pull request closed without merging**
