### PR TITLE
Improve reporting

### PR DESCRIPTION
**Pull request by chaws**
Changes in this PR were asked by Ryan Harkin and Milosz:
1. Link tests to qa-reports UI (Ryan)
2. Make schneider report generic (Milosz)
2.1. Renamed `schneider_report` to a more generic name `build_report`
2.2. Added an extra optional parameter to include optional text, which will be appropriate to generate schneider-specific reports

### CODE REVIEW

**Comment by amrohassaan** [comment]
LGTM. Merging

**Comment by mwasilew** [comment]
@chaws  you left the "schneider" name in HTML template. So this isn't really generic at this point. Also free text on top should really be a included jinja2 template so formatting is easier.

**Comment by mwasilew** [comment]
Ah, one more thing - green and red look like 1998 :P

**Comment by chaws** [comment]
@mwasilew I did `grep -rni schneider` in squad-client's root git dir and didn't find any reference to "schneider". Also in github it shows only in changelog: https://github.com/Linaro/squad-client/search?q=schneider&unscoped_q=schneider

Yeah, green/red wasn't the most brilliant idea :) 

I'll change the free-text to be jinja2 "includeable"

**Comment by mwasilew** [comment]
@chaws ah, I see now. It was still present in 6819f0e207 but removed in next commit.

**Pull request merged**
