### PR TITLE
Add submit TuxSuite command

### PR DESCRIPTION
**Pull request by chaws**
This subcommand adds support for integrating TuxSuite and SQUAD. It should be used as:

```bash
$ squad-client submit-tuxsuite \
       --group lkft \
       --project linux-stable-rc-linux-5.12.y \
       --build v5.12.19 \
       --backend tuxsuite.com \
       --json results-from-tuxsuite-cli.json
```

The outcome of this command is subsequent calls to SQUAD's `/api/watchjob` endpoint, triggering the TuxSuite backend, fetching both build and results from Tux.

### CODE REVIEW

**Comment by jscook2345** [comment]
@chaws Is this ready for review? Looks like a few local conflicts need to be resolved

**Comment by chaws** [comment]
@jscook2345 It's not yet, I'm waiting for squad to implement tuxsuite backend. @amrohassaan 's working on it.

**Comment by chaws** [comment]
I have pushed new changes to it and will rebase it tomorrow.

**Comment by chaws** [comment]
Talked to @roxell , the intention is to have squad-client send only tuxtest json result file. I think squad-client submit-tuxsuite should be as generic as possible, contemplating all 3: tuxbuild, tuxtest and tuxplan

**Comment by chaws** [comment]
Checks are green. I'm merging this now and we can continue further discussions after we run an initial pipepline with it

**Pull request merged**
