### PR TITLE
Dockerfile: refactor and switch to Alpine based image

### PR DESCRIPTION
**Pull request by fboudra**
It reduces the image size from 407MB to 270MB.

Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

### CODE REVIEW

**Comment by fboudra** [comment]
@chaws Hey Charles, I'm not sure you're interested by moving to Alpine and reduce the size of the container image. Submitting the PR and you'll let me know :)

**Comment by chaws** [comment]
Thanks for the patch, @fboudra I'm always down for container minimalism :) I'll create a new tag with the new image size

**Comment by jscook2345** [comment]
@chaws 

Please take a look at this article. I don't know if it's currently accurate, but there are some things to watch out for when using alpine for applications. I'm OK with using alpine, but keep an eye out for the follow things.

https://pythonspeed.com/articles/alpine-docker-python/

**Comment by fboudra** [comment]
@jscook2345 please stop spreading FUD. The python alpine image is a docker official and popular image used for Python applications by millions. We use it in various projects at Linaro, everyday in CI.

For squad-client use-case, those are facts:
- it's faster to build
- it's smaller
- we don't pull any pre-built wheel, we builds wheels for MarkupSafe, pyrsistent and pyyaml (FYI that's why we have build-base and yaml-dev packages installed as build dependencies)

I'm gonna skip the part of the article about Alpine Linux can cause unexpected runtime bugs. Well, this is software, there's bugs even on glibc or bionic or musl. The performance aspect seems to me irrelevant as the main point of the container is to embed squad-client, a cli that manipulate APIs and don't require to be fast or do any significant computation. And finally, squad-client usage of the thread stack siza is small. My points being many of the issues raised by the article don't apply to squad-client.

That said, as in my initial intent, I wasn't sure @chaws will be interested by this PR, but nevertheless I'm gonna happily use squad-client and lavacli in my python alpine based image in my CI.

**Pull request merged**
