### PR TITLE
Schneider test totals

### PR DESCRIPTION
**Pull request by amrohassaan**
Add wkhtmltopdf to docker dependencies and update schneider template+script to enable pdf generation, and display tests totals and summary.

### CODE REVIEW

**Comment by mwasilew** [comment]
could you rebase?

**Comment by amrohassaan** [comment]
Done

**Comment by mwasilew** [comment]
Let's merge it for the moment. It's not ideal but we need it working. I'll add my patches on top.

**Comment by chaws** [comment]
@mwasilew for that email that @amrohassaan sent to Ryan, we need to make a release. Should I make a new one now?

**Comment by mwasilew** [comment]
@chaws let me fix a few issues with the current code and we can release tomorrow.

**Pull request merged**
